### ISSUE TITLE
Question: Changes in aut_ep?

### ISSUE THREAD

**Issue by paskn** [vdeminstitute/ERT#27]
Dear all,
Could you kindly confirm or disprove this: did the number of `aut_ep`  for the U.S. change at some point?

I was trying to reproduce my older plot and found inconsistencies in `aut_ep` counts. My older plot has several episodes for the U.S. but now it is all  0? 

I am ready to accept this, I just need some sanity check. I am about to submit  a paper to a journal that uses ERT data, and some quick "yes" or "no" would help me tremendously. 

Thank you!

**Comment by abedgell** [comment]
The United States experienced one episode of autocratization in v10 and v13, which roughly corresponds to the first Trump term. However, this episode does not appear in v11, v12, and v14 (the current release) because the total decline did not meet the default cumulative inclusion parameter (0.10). The underlying data used to construct the ERT changes with each release of the V-Dem dataset. As a result, the timing of episodes may differ between ERT releases. This is particularly true for episodes that are near the cut-offs for the default parameters, such as the United States. This doesn't mean the United States was immune to autocratization; it simply did not experience substantial enough declines to meet the threshold for an episode in v14.

**Comment by paskn** [comment]
Thanks, Amanda! I'm closing this issue.
